### ISSUE TITLE
用户流量不足

### ISSUE THREAD

**Issue by icy-6** [WenyaoL/pandown-java#6]
搭建完成后，提交解析文件后，提示用户流量不足或被冻结，但是账号内有解析流量

**Comment by WenyaoL** [comment]
解析原理和项目：https://github.com/yuantuo666/baiduwp-php 一样。（都是利用SVIP账号去解析链接）
1. 请查看是否已经将SVIP账号注入到数据库中

如果注册管理员账号？
通过注册页面注册成一个普通项目账号，然后在通过在数据库pandown中pandown_user_role表中对应的user_id的role_id改为1即可

如何管理添加的百度网盘账号？
注：只有本项目的管理员账号才能进行百度云账号管理。
登录管理员账号，在账号管理页面（只有管理员才能看见）中，添加或者修改账号即可


如何添加用户账号？
注：只有本项目的管理员账号才能进行项目账号管理。
登录管理员账号，在账号管理页面（只有管理员才能看见）中，添加或者修改账号即可


本项目和baiduwp-php的差异
解析原理并没有差异，只是比baiduwp-php多了流量统计和账号管理功能

**Comment by icy-6** [comment]
已配置普通账号与svip账号，且svip账号正常，能获取到文件信息，但是点击下载文件后，提示流量不足或账号流量被冻结

**Comment by icy-6** [comment]
<img width="1280" alt="屏幕截图 2023-10-24 123657" src="https://github.com/WenyaoL/pandown-java/assets/77364575/b4c171c9-71b0-4990-90f3-d7e55658e64f">
<img width="1280" alt="屏幕截图 2023-10-24 123710" src="https://github.com/WenyaoL/pandown-java/assets/77364575/8dd857bc-567b-4007-a9e7-b8848aaacdcb">
<img width="1280" alt="屏幕截图 2023-10-24 123819" src="https://github.com/WenyaoL/pandown-java/assets/77364575/68267d7e-8fde-4f17-9aa7-10b2345455b6">

<img width="1278" alt="屏幕截图 2023-10-24 123719" src="https://github.com/WenyaoL/pandown-java/assets/77364575/cf2ea932-ed69-4444-b1f0-7e44005e306e">

**Comment by Sam521** [comment]
RequestService类中requestSvipDlink方法。224行
org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [no body]

**Comment by WenyaoL** [comment]
项目已经更新（可以参试新版本的代码是否也有该问题）
我在本地跑该项目暂时没出现上面问题。
或许我需要更多的信息去修复这个BUG，可否提供本地IDEA中异常错误的打印信息。我需要更加准确信息来定位问题所在

**Comment by Sam521** [comment]
![image](https://github.com/WenyaoL/pandown-java/assets/25532905/f5a0b85b-9e4c-451a-9270-74dd58d7a86a)

http调用的时候出现的问题，有可能是cookie或者bduss抓得不对？

**Comment by WenyaoL** [comment]
代码已经更新，可以pull下来运行一下，看是否还有该问题
注意：添加SVIP时,BDUSS和STOKEN只填值的部分，如：
**(BDUSS=XXX;STOKEN=XXX;)只取XXX部分**
